(function(){
'use strict';
const themes={wood:{name:'Madera clásica',panel:'#5b3825',ink:'#f4dfab'},black:{name:'Negro y dorado',panel:'#111511',ink:'#ead49a'},gold:{name:'Dorado y madera',panel:'#e5ce91',ink:'#211b14'}};
function periodLabel(kind,period){if(kind==='year')return String(period);if(!/^\d{4}-\d{2}$/.test(period))return String(period);return new Date(period+'-15T12:00:00Z').toLocaleDateString('es-PE',{month:'long',year:'numeric',timeZone:'UTC'});}
const monthThemes={wood:{name:'Marfil y verde',background:'#f4f0e5',ink:'#234c3e',accent:'#3c8269'},black:{name:'Azul noche y plata',background:'#082647',ink:'#f3f5f6',accent:'#c9d7e1'},gold:{name:'Verde esmeralda',background:'#123e34',ink:'#fff8e8',accent:'#a8d8c4'}};
async function drawMonth(entry,period,theme){
const canvas=document.createElement('canvas');canvas.width=1200;canvas.height=1500;const c=canvas.getContext('2d'),p=monthThemes[theme]||monthThemes.black;
c.fillStyle=p.background;c.fillRect(0,0,1200,1500);
let seed=31;function rand(){seed=(seed*16807)%2147483647;return seed/2147483647;}
for(let i=0;i<850;i++){const x=rand()*1200,y=rand()*1500;if(y>235&&y<1230&&x>110&&x<1090)continue;c.globalAlpha=.15+rand()*.4;c.fillStyle=p.accent;c.beginPath();c.arc(x,y,1+rand()*3,0,Math.PI*2);c.fill();}c.globalAlpha=1;
const logo=new Image();logo.src='./logo-vismo-personal.png';await logo.decode();const stamp=document.createElement('canvas');stamp.width=260;stamp.height=Math.ceil(260*logo.height/logo.width);const lc=stamp.getContext('2d');lc.drawImage(logo,0,0,stamp.width,stamp.height);lc.globalCompositeOperation='source-in';lc.fillStyle=p.ink;lc.fillRect(0,0,stamp.width,stamp.height);c.drawImage(stamp,470,65);
c.save();c.beginPath();c.arc(600,460,245,0,Math.PI*2);c.clip();c.fillStyle=theme==='wood'?'#e0e8dd':'#325b65';c.fillRect(355,215,490,490);
if(entry.image){const photo=new Image();photo.src=entry.image;await photo.decode();const size=Math.min(photo.width,photo.height);c.drawImage(photo,(photo.width-size)/2,(photo.height-size)/2,size,size,355,215,490,490);}else{c.fillStyle=p.ink;c.textAlign='center';c.font='100px Georgia';c.fillText(String(entry.name||'VISMO').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join(''),600,490);}c.restore();c.strokeStyle=p.accent;c.lineWidth=8;c.beginPath();c.arc(600,460,245,0,Math.PI*2);c.stroke();
const ribbon=c.createLinearGradient(200,570,1000,760);ribbon.addColorStop(0,p.accent);ribbon.addColorStop(.5,theme==='wood'?'#b7dfcc':'#f4f7f5');ribbon.addColorStop(1,p.accent);c.fillStyle=ribbon;
c.beginPath();c.moveTo(210,555);c.bezierCurveTo(260,645,400,595,510,690);c.lineTo(470,760);c.bezierCurveTo(370,680,240,720,170,630);c.lineTo(225,635);c.closePath();c.fill();c.beginPath();c.moveTo(990,555);c.bezierCurveTo(940,645,800,595,690,690);c.lineTo(730,760);c.bezierCurveTo(830,680,960,720,1030,630);c.lineTo(975,635);c.closePath();c.fill();
c.beginPath();for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,r=i%2?58:125;const x=600+Math.cos(a)*r,y=700+Math.sin(a)*r;i?c.lineTo(x,y):c.moveTo(x,y);}c.closePath();c.fill();c.strokeStyle=p.accent;c.lineWidth=5;c.stroke();
c.textAlign='center';c.fillStyle=p.ink;
function block(value,y,size,maxHeight,bold=false){let rows;do{c.font=(bold?'bold ':'')+size+'px Georgia';rows=[];let line='';for(const word of String(value||'').split(/\s+/)){const next=line?line+' '+word:word;if(line&&c.measureText(next).width>970){rows.push(line);line=word}else line=next;}if(line)rows.push(line);if(rows.length*size*1.3<=maxHeight)break;size--;}while(size>16);rows.forEach((line,i)=>c.fillText(line,600,y+i*size*1.3,970));}
c.font='32px Georgia';c.fillText('TRABAJADOR DEL MES',600,875);block(entry.name,955,64,150,true);c.font='italic 30px Georgia';c.fillText(periodLabel('month',period),600,1120);block(entry.message||'Gracias por tu esfuerzo y dedicación.',1200,32,140);if(entry.virtues)block(entry.virtues,1400,25,60,true);return canvas;
}

async function draw(entry,kind,period,theme){
if(kind==='month')return drawMonth(entry,period,theme);
const canvas=document.createElement('canvas');canvas.width=1200;canvas.height=1500;const ctx=canvas.getContext('2d'),palette=themes[theme]||themes.black;
const wood=ctx.createLinearGradient(0,0,1200,1500);wood.addColorStop(0,'#75503a');wood.addColorStop(.45,'#382117');wood.addColorStop(1,'#79543c');ctx.fillStyle=wood;ctx.fillRect(0,0,1200,1500);
for(let i=0;i<150;i++){ctx.strokeStyle=i%2?'rgba(236,180,120,.12)':'rgba(20,8,3,.16)';ctx.lineWidth=1+i%3;ctx.beginPath();const x=i*8;ctx.moveTo(x,0);ctx.bezierCurveTo(x+12,500,x-10,1000,x+4,1500);ctx.stroke();}
ctx.strokeStyle='#9b7355';ctx.lineWidth=14;ctx.strokeRect(22,22,1156,1456);ctx.strokeStyle='#291a12';ctx.lineWidth=12;ctx.strokeRect(58,58,1084,1384);
ctx.fillStyle=palette.panel;ctx.fillRect(90,90,1020,1320);if(theme==='gold'){const gold=ctx.createLinearGradient(90,90,1110,1410);gold.addColorStop(0,'#f5e7b7');gold.addColorStop(.5,'#ceac62');gold.addColorStop(1,'#efdfaa');ctx.fillStyle=gold;ctx.fillRect(90,90,1020,1320);}
ctx.strokeStyle=theme==='gold'?'#292015':'#c9aa65';ctx.lineWidth=8;ctx.strokeRect(114,114,972,1272);
const logo=new Image();logo.src=theme==='gold'?'./logo-vismo-personal.png':'./logo-vismo-blanco.png';await logo.decode();const logoWidth=260,logoHeight=logoWidth*logo.height/logo.width,logoStamp=document.createElement("canvas");logoStamp.width=logoWidth;logoStamp.height=Math.ceil(logoHeight);const stamp=logoStamp.getContext("2d");stamp.drawImage(logo,0,0,logoWidth,logoHeight);stamp.globalCompositeOperation="source-in";stamp.fillStyle=palette.ink;stamp.fillRect(0,0,logoWidth,logoHeight);ctx.drawImage(logoStamp,600-logoWidth/2,155,logoWidth,logoHeight);
ctx.textAlign='center';ctx.fillStyle=palette.ink;
function lines(text,size,width){ctx.font=size+'px Georgia';let result=[],line='';for(const word of String(text||'').split(/\s+/)){const candidate=line?line+' '+word:word;if(line&&ctx.measureText(candidate).width>width){result.push(line);line=word}else line=candidate;}if(line)result.push(line);return result;}
function text(value,y,size,maxWidth,maxHeight,bold){let rows;do{rows=lines(value,size,maxWidth);if(rows.length*size*1.35<=maxHeight)break;size--;}while(size>14);ctx.font=(bold?'bold ':'')+size+'px Georgia';rows.forEach((line,i)=>ctx.fillText(line,600,y+i*size*1.35,maxWidth));return rows.length*size*1.35;}
text(kind==='year'?'TRABAJADOR DEL AÑO':'TRABAJADOR DEL MES',335,47,860,135,true);text(periodLabel(kind,period),440,34,860,65,false);
ctx.font='italic 35px Georgia';ctx.fillText('Reconocimiento otorgado a',600,545);
text(entry.name,625,58,840,165,true);
ctx.strokeStyle=palette.ink;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(245,830);ctx.lineTo(530,830);ctx.moveTo(670,830);ctx.lineTo(955,830);ctx.stroke();ctx.font='38px Georgia';ctx.fillText('✦',600,843);
text(entry.message||'Por tu compromiso, dedicación y valioso aporte al equipo VISMO.',915,33,830,265,false);
if(entry.virtues)text(entry.virtues,1230,26,830,65,true);
ctx.font='bold 30px Georgia';ctx.fillText('VISMO',600,1320);ctx.font='20px Georgia';ctx.fillText('Visión y modernidad para vivir mejor',600,1355);
return canvas;
}
function Plaque({react:React,entry,kind,period}){const[open,setOpen]=React.useState(false),[theme,setTheme]=React.useState(entry.plaqueTheme||'black'),[preview,setPreview]=React.useState(''),[error,setError]=React.useState(''),[busy,setBusy]=React.useState(false);
React.useEffect(()=>{if(!open)return;let active=true;setPreview('');setError('');draw(entry,kind,period,theme).then(canvas=>{if(active)setPreview(canvas.toDataURL('image/png'))}).catch(err=>{if(active)setError(err.message)});return()=>{active=false}},[open,theme,entry.name,entry.message,entry.virtues,entry.image,kind,period]);
async function download(){setBusy(true);setError('');try{const canvas=await draw(entry,kind,period,theme);const blob=await new Promise((resolve,reject)=>canvas.toBlob(value=>value?resolve(value):reject(Error('No se pudo generar la placa.')),'image/png'));const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='VISMO-'+kind+'-'+period+'-'+String(entry.name||'trabajador').replace(/[^\p{L}\p{N}]+/gu,'-')+'.png';link.click();setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(err){setError(err.message)}finally{setBusy(false)}}
return React.createElement('div',{className:'vismo-plaque'},React.createElement('button',{type:'button',onClick:()=>setOpen(!open)},open?'Cerrar placa':'Mi placa de reconocimiento'),open&&React.createElement(React.Fragment,null,React.createElement('p',null,'Diseño elegido por administración: '+(kind==='month'?monthThemes:themes)[theme].name),preview?React.createElement('img',{src:preview,alt:'Placa de reconocimiento de '+entry.name,style:{display:'block',width:'100%',maxWidth:360,height:'auto',margin:'16px auto'}}):!error&&React.createElement('p',{role:'status'},'Preparando placa…'),React.createElement('button',{type:'button',className:'primary',disabled:busy||!preview,onClick:download},busy?'Generando…':'Descargar mi placa · PNG'),error&&React.createElement('p',{role:'alert'},error)));
}
function Preview({react:R,entry,kind,period,onChange}){const[images,setImages]=R.useState({}),[error,setError]=R.useState('');R.useEffect(()=>{let active=true;setImages({});setError('');Promise.all(Object.keys(themes).map(async key=>[key,(await draw(entry,kind,period,key)).toDataURL('image/png')])).then(rows=>{if(active)setImages(Object.fromEntries(rows))}).catch(err=>{if(active)setError(err.message)});return()=>{active=false}},[entry.name,entry.message,entry.virtues,entry.image,kind,period]);return R.createElement('div',null,R.createElement('h4',null,'Elige la placa que podrá descargar'),R.createElement('div',{className:'award-designs'},Object.entries(kind==='month'?monthThemes:themes).map(([key,value])=>R.createElement('label',{key,className:'award-choice'},R.createElement('input',{type:'radio',name:'plaque-'+entry.worker,value:key,checked:(entry.plaqueTheme||'black')===key,onChange:()=>onChange(key)}),value.name,images[key]?R.createElement('img',{src:images[key],alt:value.name+' para '+(entry.name||'el trabajador')}):R.createElement('p',null,'Preparando vista previa…')))),error&&R.createElement('p',{role:'alert'},error));}
function Ribbon({react:R,kind,period}){return R.createElement('span',{className:'award-ribbon '+kind,title:'Trabajador del '+(kind==='year'?'año':'mes')+' · '+periodLabel(kind,period)},R.createElement('span',{className:'award-seal','aria-hidden':true},'★'),R.createElement('span',null,(kind==='year'?'Trabajador del año':'Trabajador del mes')+' · '+periodLabel(kind,period)));}
function Profiles({react:R,cards,worker}){const people=new Map();for(const c of cards){if(!['year','month'].includes(c.kind))continue;for(const entry of c.published?.entries||[]){if(!people.has(entry.worker))people.set(entry.worker,{name:entry.name,awards:[]});people.get(entry.worker).awards.push({kind:c.kind,period:c.period,entry});}}if(!people.size)return null;return R.createElement('section',{className:'award-profiles'},R.createElement('h3',null,'Compañeros reconocidos'),Array.from(people,([id,p])=>R.createElement('article',{key:id,className:'award-profile'},R.createElement('h4',null,p.name,id===worker?' · Mi perfil':''),p.awards.map(a=>R.createElement('div',{key:a.kind+a.period},R.createElement(Ribbon,{react:R,kind:a.kind,period:a.period}),id===worker&&R.createElement(Plaque,{react:R,entry:a.entry,kind:a.kind,period:a.period}))))));}
window.VismoAwardPreview=Preview;window.VismoAwardRibbon=Ribbon;window.VismoAwardProfiles=Profiles;window.VismoAwardPlaque=Plaque;
})();
